<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B_7pWxFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b.7pWxF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b.7pWxF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'id' => ['privates', '.errored..service_locator.b.7pWxF.App\\Entity\\Agent', NULL, 'Cannot autowire service ".service_locator.b.7pWxF": it references class "App\\Entity\\Agent" but no such service exists.'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'id' => 'App\\Entity\\Agent',
            'slugger' => '?',
        ]);
    }
}
