<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VAt9u8OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VAt9u8O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VAt9u8O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'departementRepository' => ['privates', 'App\\Repository\\DepartementRepository', 'getDepartementRepositoryService', true],
            'localite' => ['privates', '.errored..service_locator.VAt9u8O.App\\Entity\\Localite', NULL, 'Cannot autowire service ".service_locator.VAt9u8O": it references class "App\\Entity\\Localite" but no such service exists.'],
            'localiteRepository' => ['privates', 'App\\Repository\\LocaliteRepository', 'getLocaliteRepositoryService', true],
        ], [
            'departementRepository' => 'App\\Repository\\DepartementRepository',
            'localite' => 'App\\Entity\\Localite',
            'localiteRepository' => 'App\\Repository\\LocaliteRepository',
        ]);
    }
}
