<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K8Un60RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K8Un60R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K8Un60R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
            'proprietaireRepository' => ['privates', 'App\\Repository\\ProprietaireRepository', 'getProprietaireRepositoryService', true],
        ], [
            'installationRepository' => 'App\\Repository\\InstallationRepository',
            'proprietaireRepository' => 'App\\Repository\\ProprietaireRepository',
        ]);
    }
}
