<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XYgrrPlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XYgrrPl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XYgrrPl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agent' => ['privates', '.errored..service_locator.XYgrrPl.App\\Entity\\Agent', NULL, 'Cannot autowire service ".service_locator.XYgrrPl": it references class "App\\Entity\\Agent" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'agent' => 'App\\Entity\\Agent',
            'doctrine' => '?',
        ]);
    }
}
