<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7Uj5Nf1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7Uj5Nf1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Uj5Nf1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'natureTravauxRepository' => ['privates', 'App\\Repository\\NatureTravauxRepository', 'getNatureTravauxRepositoryService', true],
        ], [
            'natureTravauxRepository' => 'App\\Repository\\NatureTravauxRepository',
        ]);
    }
}
