<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LrBnh3_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LrBnh3.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LrBnh3.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'id' => ['privates', '.errored..service_locator.LrBnh3..App\\Entity\\Agence', NULL, 'Cannot autowire service ".service_locator.LrBnh3.": it references class "App\\Entity\\Agence" but no such service exists.'],
        ], [
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'id' => 'App\\Entity\\Agence',
        ]);
    }
}
