<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R2LWlfuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r2LWlfu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r2LWlfu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agence' => ['privates', '.errored..service_locator.r2LWlfu.App\\Entity\\Agence', NULL, 'Cannot autowire service ".service_locator.r2LWlfu": it references class "App\\Entity\\Agence" but no such service exists.'],
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'agence' => 'App\\Entity\\Agence',
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'doctrine' => '?',
        ]);
    }
}
