<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KN8rBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kN8r__B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kN8r__B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'natureTravaux' => ['privates', '.errored..service_locator.kN8r__B.App\\Entity\\NatureTravaux', NULL, 'Cannot autowire service ".service_locator.kN8r__B": it references class "App\\Entity\\NatureTravaux" but no such service exists.'],
            'natureTravauxRepository' => ['privates', 'App\\Repository\\NatureTravauxRepository', 'getNatureTravauxRepositoryService', true],
        ], [
            'natureTravaux' => 'App\\Entity\\NatureTravaux',
            'natureTravauxRepository' => 'App\\Repository\\NatureTravauxRepository',
        ]);
    }
}
