<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LrBnh3..App\Entity\Agence' shared service.
     *
     * @return \App\Entity\Agence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LrBnh3.": it references class "App\\Entity\\Agence" but no such service exists.');
    }
}
