<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Mzx.7jn.App\Entity\Departement' shared service.
     *
     * @return \App\Entity\Departement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Mzx.7jn": it references class "App\\Entity\\Departement" but no such service exists.');
    }
}
