<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocaliteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VAt9u8O.App\Entity\Localite' shared service.
     *
     * @return \App\Entity\Localite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VAt9u8O": it references class "App\\Entity\\Localite" but no such service exists.');
    }
}
