<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNatureBatimentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4kMmtjc.App\Entity\NatureBatiment' shared service.
     *
     * @return \App\Entity\NatureBatiment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4kMmtjc": it references class "App\\Entity\\NatureBatiment" but no such service exists.');
    }
}
