<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNatureTravauxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gwOtzPA.App\Entity\NatureTravaux' shared service.
     *
     * @return \App\Entity\NatureTravaux
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gwOtzPA": it references class "App\\Entity\\NatureTravaux" but no such service exists.');
    }
}
