<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProprietaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O2.8t0h.App\Entity\Proprietaire' shared service.
     *
     * @return \App\Entity\Proprietaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O2.8t0h": it references class "App\\Entity\\Proprietaire" but no such service exists.');
    }
}
