<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q.unGQl.App\Entity\Region' shared service.
     *
     * @return \App\Entity\Region
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q.unGQl": it references class "App\\Entity\\Region" but no such service exists.');
    }
}
