<?php

namespace ContainerQuesjqN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeConstruction2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hHMqbLc.App\Entity\TypeConstruction' shared service.
     *
     * @return \App\Entity\TypeConstruction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hHMqbLc": it references class "App\\Entity\\TypeConstruction" but no such service exists.');
    }
}
