<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HfeDCOrService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.hfeDCOr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hfeDCOr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'pgn' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'remboursementRepository' => ['privates', 'App\\Repository\\RemboursementRepository', 'getRemboursementRepositoryService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'doctrine' => '?',
            'pgn' => '?',
            'remboursementRepository' => 'App\\Repository\\RemboursementRepository',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
