<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3JoCPfoService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3JoCPfo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3JoCPfo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'departementRepository' => ['privates', 'App\\Repository\\DepartementRepository', 'getDepartementRepositoryService', true],
            'pgn' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'departementRepository' => 'App\\Repository\\DepartementRepository',
            'pgn' => '?',
        ]);
    }
}
