<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rs2zctService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rs2zct_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rs2zct_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'id' => ['privates', '.errored..service_locator.rs2zct_.App\\Entity\\Agence', NULL, 'Cannot autowire service ".service_locator.rs2zct_": it references class "App\\Entity\\Agence" but no such service exists.'],
            'localiteRepository' => ['privates', 'App\\Repository\\LocaliteRepository', 'getLocaliteRepositoryService', true],
        ], [
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'doctrine' => '?',
            'id' => 'App\\Entity\\Agence',
            'localiteRepository' => 'App\\Repository\\LocaliteRepository',
        ]);
    }
}
