<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5WRlIr_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5WRlIr.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5WRlIr.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'installation' => ['privates', '.errored..service_locator.5WRlIr..App\\Entity\\Installation', NULL, 'Cannot autowire service ".service_locator.5WRlIr.": it references class "App\\Entity\\Installation" but no such service exists.'],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'doctrine' => '?',
            'installation' => 'App\\Entity\\Installation',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
