<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QA7FXgBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qA7FXgB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qA7FXgB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pgn' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService', true],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'pgn' => '?',
            'profilRepository' => 'App\\Repository\\ProfilRepository',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
