<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AjKA78JService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ajKA78J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ajKA78J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeConstruction' => ['privates', '.errored..service_locator.ajKA78J.App\\Entity\\TypeConstruction', NULL, 'Cannot autowire service ".service_locator.ajKA78J": it references class "App\\Entity\\TypeConstruction" but no such service exists.'],
            'typeConstructionRepository' => ['privates', 'App\\Repository\\TypeConstructionRepository', 'getTypeConstructionRepositoryService', true],
        ], [
            'typeConstruction' => 'App\\Entity\\TypeConstruction',
            'typeConstructionRepository' => 'App\\Repository\\TypeConstructionRepository',
        ]);
    }
}
