<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4rjmSlsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.4rjmSls' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4rjmSls'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'electricienRepository' => ['privates', 'App\\Repository\\ElectricienRepository', 'getElectricienRepositoryService', true],
            'installation' => ['privates', '.errored..service_locator.4rjmSls.App\\Entity\\Installation', NULL, 'Cannot autowire service ".service_locator.4rjmSls": it references class "App\\Entity\\Installation" but no such service exists.'],
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
            'pjRepository' => ['privates', 'App\\Repository\\PieceJointeRepository', 'getPieceJointeRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'electricienRepository' => 'App\\Repository\\ElectricienRepository',
            'installation' => 'App\\Entity\\Installation',
            'installationRepository' => 'App\\Repository\\InstallationRepository',
            'pjRepository' => 'App\\Repository\\PieceJointeRepository',
            'slugger' => '?',
        ]);
    }
}
