<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XGDK4qbService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xGDK4qb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xGDK4qb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'dossier' => ['privates', '.errored..service_locator.xGDK4qb.App\\Entity\\Dossier', NULL, 'Cannot autowire service ".service_locator.xGDK4qb": it references class "App\\Entity\\Dossier" but no such service exists.'],
            'dossierRepository' => ['privates', 'App\\Repository\\DossierRepository', 'getDossierRepositoryService', true],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'doctrine' => '?',
            'dossier' => 'App\\Entity\\Dossier',
            'dossierRepository' => 'App\\Repository\\DossierRepository',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
