<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pz66VkaService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.pz66Vka' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pz66Vka'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeConstructionRepository' => ['privates', 'App\\Repository\\TypeConstructionRepository', 'getTypeConstructionRepositoryService', true],
        ], [
            'typeConstructionRepository' => 'App\\Repository\\TypeConstructionRepository',
        ]);
    }
}
