<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_87wqDcSService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.87wqDcS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.87wqDcS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pointNonconfRepository' => ['privates', 'App\\Repository\\PointNonconfRepository', 'getPointNonconfRepositoryService', true],
        ], [
            'pointNonconfRepository' => 'App\\Repository\\PointNonconfRepository',
        ]);
    }
}
