<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DFSe6ZzService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.dFSe6Zz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dFSe6Zz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rapportRepository' => ['privates', 'App\\Repository\\RapportRepository', 'getRapportRepositoryService', true],
        ], [
            'rapportRepository' => 'App\\Repository\\RapportRepository',
        ]);
    }
}
