<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LAgBKEmService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.LAgBKEm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LAgBKEm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'id' => ['privates', '.errored..service_locator.LAgBKEm.App\\Entity\\Agence', NULL, 'Cannot autowire service ".service_locator.LAgBKEm": it references class "App\\Entity\\Agence" but no such service exists.'],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'id' => 'App\\Entity\\Agence',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
