<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9SKKdqAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9SKKdqA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9SKKdqA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agaffRepository' => ['privates', 'App\\Repository\\AffectationsAgentsRepository', 'getAffectationsAgentsRepositoryService', true],
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'agent' => ['privates', '.errored..service_locator.9SKKdqA.App\\Entity\\Agent', NULL, 'Cannot autowire service ".service_locator.9SKKdqA": it references class "App\\Entity\\Agent" but no such service exists.'],
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'agaffRepository' => 'App\\Repository\\AffectationsAgentsRepository',
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'agent' => 'App\\Entity\\Agent',
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'doctrine' => '?',
        ]);
    }
}
