<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.MqnLKQi.App\Entity\Agent' shared service.
     *
     * @return \App\Entity\Agent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MqnLKQi": it references class "App\\Entity\\Agent" but no such service exists.');
    }
}
