<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DemandeRepository' shared autowired service.
     *
     * @return \App\Repository\DemandeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DemandeRepository'] = new \App\Repository\DemandeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
