<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossier9Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xGDK4qb.App\Entity\Dossier' shared service.
     *
     * @return \App\Entity\Dossier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xGDK4qb": it references class "App\\Entity\\Dossier" but no such service exists.');
    }
}
