<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElectricienService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0P9Tnhm.App\Entity\Electricien' shared service.
     *
     * @return \App\Entity\Electricien
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0P9Tnhm": it references class "App\\Entity\\Electricien" but no such service exists.');
    }
}
