<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElectricienRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ElectricienRepository' shared autowired service.
     *
     * @return \App\Repository\ElectricienRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ElectricienRepository'] = new \App\Repository\ElectricienRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
