<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeocodeCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Bazinga\GeocoderBundle\Command\GeocodeCommand' shared service.
     *
     * @return \Bazinga\GeocoderBundle\Command\GeocodeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Bazinga\\GeocoderBundle\\Command\\GeocodeCommand'] = $instance = new \Bazinga\GeocoderBundle\Command\GeocodeCommand(($container->privates['Geocoder\\ProviderAggregator'] ?? $container->load('getProviderAggregatorService')));

        $instance->setName('geocoder:geocode');

        return $instance;
    }
}
