<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\InstallationController' shared autowired service.
     *
     * @return \App\Controller\InstallationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\InstallationController'] = $instance = new \App\Controller\InstallationController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\InstallationController', $container));

        return $instance;
    }
}
