<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNatureTravauxControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\NatureTravauxController' shared autowired service.
     *
     * @return \App\Controller\NatureTravauxController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\NatureTravauxController'] = $instance = new \App\Controller\NatureTravauxController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\NatureTravauxController', $container));

        return $instance;
    }
}
