<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaiement2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.SOiIyr0.App\Entity\Paiement' shared service.
     *
     * @return \App\Entity\Paiement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SOiIyr0": it references class "App\\Entity\\Paiement" but no such service exists.');
    }
}
