<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointVerificationService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.BSB4jH_.App\Entity\PointVerification' shared service.
     *
     * @return \App\Entity\PointVerification
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BSB4jH_": it references class "App\\Entity\\PointVerification" but no such service exists.');
    }
}
