<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRapport2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.9ci93Eg.App\Entity\Rapport' shared service.
     *
     * @return \App\Entity\Rapport
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9ci93Eg": it references class "App\\Entity\\Rapport" but no such service exists.');
    }
}
