<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemboursementService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.JYhPrRB.App\Entity\Remboursement' shared service.
     *
     * @return \App\Entity\Remboursement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JYhPrRB": it references class "App\\Entity\\Remboursement" but no such service exists.');
    }
}
