<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_AccessMapService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.access_map' shared service.
     *
     * @return \Symfony\Component\Security\Http\AccessMap
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/main'), [0 => 'IS_AUTHENTICATED_FULLY', 1 => 'ROLE_USER'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/region'), [0 => 'ROLE_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/departement'), [0 => 'ROLE_ACCUEIL', 1 => 'ROLE_RFO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/localite'), [0 => 'ROLE_ACCUEIL', 1 => 'ROLE_RFO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/agence'), [0 => 'ROLE_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/agent'), [0 => 'ROLE_ADMIN'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/electricien'), [0 => 'ROLE_ACCUEIL', 1 => 'ROLE_RFO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/proprietaire'), [0 => 'ROLE_ACCUEIL', 1 => 'ROLE_RFO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/installation/soumission'), [0 => 'ROLE_PUBLIC', 1 => 'ROLE_RFO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/installation/paiement'), [0 => 'ROLE_CAISSIER', 1 => 'ROLE_COMPTABLE'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/installation/validation'), [0 => 'ROLE_RFO'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dossier/affectation'), [0 => 'ROLE_REFERENT'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dossier/visite'), [0 => 'ROLE_CONTROLEUR'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dossier/rapport'), [0 => 'ROLE_CONTROLEUR'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/utilisateur'), [0 => 'ROLE_USER'], NULL);

        return $instance;
    }
}
