<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Services\Tools' shared autowired service.
     *
     * @return \App\Services\Tools
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Services\\Tools'] = new \App\Services\Tools(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['http_client'] ?? $container->load('getHttpClientService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), new \Endroid\QrCode\Builder\Builder(), 'yatamala.net@gmail.com', 'Notification COSSUEL');
    }
}
