<?php

namespace ContainerE86xryi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWkbService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Geocoder\Dumper\Wkb' shared service.
     *
     * @return \Geocoder\Dumper\Wkb
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Geocoder\\Dumper\\Wkb'] = new \Geocoder\Dumper\Wkb();
    }
}
