#!/bin/sh
#rsync -av ./ cossuelapp@144.91.93.102:/home/cossuelapp/www/appcossuel/ --include=public/.htaccess  --include=vendor --exclude-from=.gitignore --exclude=.git*
rsync -av ./ root@45.80.152.165:/var/www/vhosts/yatamala.com/httpdocs/cossuel/ --include=public/.htaccess  --exclude-from=.gitignore --exclude=.git*
