<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220508141033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE profil (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE accueil');
        $this->addSql('DROP TABLE caissier');
        $this->addSql('DROP TABLE comptable');
        $this->addSql('DROP TABLE controleur');
        $this->addSql('DROP TABLE daf');
        $this->addSql('DROP TABLE referent');
        $this->addSql('DROP TABLE respo_front_office');
        $this->addSql('ALTER TABLE affectations_agents CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE affectations_agents ADD CONSTRAINT FK_73154BD725330D FOREIGN KEY (agence_id) REFERENCES agence (id)');
        $this->addSql('ALTER TABLE affectations_agents ADD CONSTRAINT FK_73154B3414710B FOREIGN KEY (agent_id) REFERENCES agent (id)');
        $this->addSql('CREATE INDEX IDX_73154BD725330D ON affectations_agents (agence_id)');
        $this->addSql('CREATE INDEX IDX_73154B3414710B ON affectations_agents (agent_id)');
        $this->addSql('ALTER TABLE agence CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE agence ADD CONSTRAINT FK_64C19AA9924DD2B5 FOREIGN KEY (localite_id) REFERENCES localite (id)');
        $this->addSql('CREATE INDEX IDX_64C19AA9924DD2B5 ON agence (localite_id)');
        $this->addSql('ALTER TABLE agent ADD profil_id INT DEFAULT NULL, ADD id_agence INT DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE photo photo VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D275ED078 FOREIGN KEY (profil_id) REFERENCES profil (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_268B9C9DE7927C74 ON agent (email)');
        $this->addSql('CREATE INDEX IDX_268B9C9D275ED078 ON agent (profil_id)');
        $this->addSql('ALTER TABLE attestation CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_326EC63F611C0C56 ON attestation (dossier_id)');
        $this->addSql('ALTER TABLE demande ADD id_paiement INT DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5167B88B4 FOREIGN KEY (installation_id) REFERENCES installation (id)');
        $this->addSql('CREATE INDEX IDX_2694D7A5FB88E14F ON demande (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_2694D7A5167B88B4 ON demande (installation_id)');
        $this->addSql('ALTER TABLE departement CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B6398260155 FOREIGN KEY (region_id) REFERENCES region (id)');
        $this->addSql('CREATE INDEX IDX_C1765B6398260155 ON departement (region_id)');
        $this->addSql('ALTER TABLE detail_verification CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE detail_verification ADD CONSTRAINT FK_46F2AF043BD38833 FOREIGN KEY (rubrique_id) REFERENCES rubrique (id)');
        $this->addSql('ALTER TABLE detail_verification ADD CONSTRAINT FK_46F2AF041623CB0A FOREIGN KEY (verification_id) REFERENCES verification (id)');
        $this->addSql('CREATE INDEX IDX_46F2AF043BD38833 ON detail_verification (rubrique_id)');
        $this->addSql('CREATE INDEX IDX_46F2AF041623CB0A ON detail_verification (verification_id)');
        $this->addSql('ALTER TABLE dossier ADD visite TINYINT(1) DEFAULT NULL, ADD rapport TINYINT(1) DEFAULT NULL, ADD attestation TINYINT(1) DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE heure_creation heure_creation DATETIME DEFAULT NULL, CHANGE date_cloture date_cloture DATETIME DEFAULT NULL, CHANGE affecte affecte TINYINT(1) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E03780E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037F4CF9AD9 FOREIGN KEY (respo_front_office_id) REFERENCES agent (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037B13E6101 FOREIGN KEY (controleur_id) REFERENCES agent (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E03735E47E35 FOREIGN KEY (referent_id) REFERENCES agent (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E03780E95E18 ON dossier (demande_id)');
        $this->addSql('CREATE INDEX IDX_3D48E037F4CF9AD9 ON dossier (respo_front_office_id)');
        $this->addSql('CREATE INDEX IDX_3D48E037B13E6101 ON dossier (controleur_id)');
        $this->addSql('CREATE INDEX IDX_3D48E03735E47E35 ON dossier (referent_id)');
        $this->addSql('ALTER TABLE electricien CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE electricien ADD CONSTRAINT FK_DFB53AEA924DD2B5 FOREIGN KEY (localite_id) REFERENCES localite (id)');
        $this->addSql('CREATE INDEX IDX_DFB53AEA924DD2B5 ON electricien (localite_id)');
        $this->addSql('ALTER TABLE grille CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE installation CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE installation ADD CONSTRAINT FK_1CBA6AB176C50E4A FOREIGN KEY (proprietaire_id) REFERENCES proprietaire (id)');
        $this->addSql('ALTER TABLE installation ADD CONSTRAINT FK_1CBA6AB15C9609E3 FOREIGN KEY (electricien_id) REFERENCES electricien (id)');
        $this->addSql('ALTER TABLE installation ADD CONSTRAINT FK_1CBA6AB1924DD2B5 FOREIGN KEY (localite_id) REFERENCES localite (id)');
        $this->addSql('ALTER TABLE installation ADD CONSTRAINT FK_1CBA6AB1387C850E FOREIGN KEY (type_construction_id) REFERENCES type_construction (id)');
        $this->addSql('ALTER TABLE installation ADD CONSTRAINT FK_1CBA6AB1B871F14F FOREIGN KEY (nature_batiment_id) REFERENCES nature_batiment (id)');
        $this->addSql('ALTER TABLE installation ADD CONSTRAINT FK_1CBA6AB178EB7775 FOREIGN KEY (nature_travaux_id) REFERENCES nature_travaux (id)');
        $this->addSql('CREATE INDEX IDX_1CBA6AB176C50E4A ON installation (proprietaire_id)');
        $this->addSql('CREATE INDEX IDX_1CBA6AB15C9609E3 ON installation (electricien_id)');
        $this->addSql('CREATE INDEX IDX_1CBA6AB1924DD2B5 ON installation (localite_id)');
        $this->addSql('CREATE INDEX IDX_1CBA6AB1387C850E ON installation (type_construction_id)');
        $this->addSql('CREATE INDEX IDX_1CBA6AB1B871F14F ON installation (nature_batiment_id)');
        $this->addSql('CREATE INDEX IDX_1CBA6AB178EB7775 ON installation (nature_travaux_id)');
        $this->addSql('ALTER TABLE localite CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE localite ADD CONSTRAINT FK_F5D7E4A9CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('CREATE INDEX IDX_F5D7E4A9CCF9E01E ON localite (departement_id)');
        $this->addSql('ALTER TABLE nature_batiment CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE nature_travaux CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE paiement ADD observation VARCHAR(255) DEFAULT NULL, DROP libelle, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE date_paiement date_paiement DATETIME DEFAULT NULL, CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE motif_remboursement motif_remboursement VARCHAR(255) DEFAULT NULL, CHANGE motif_rejet motif_rejet VARCHAR(255) DEFAULT NULL, CHANGE etat_rembousement etat_rembousement VARCHAR(255) DEFAULT NULL, CHANGE date_facture date_saisie DATETIME NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E80E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EBA52A149 FOREIGN KEY (comptable_id) REFERENCES agent (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1DC7A1E80E95E18 ON paiement (demande_id)');
        $this->addSql('CREATE INDEX IDX_B1DC7A1EBA52A149 ON paiement (comptable_id)');
        $this->addSql('ALTER TABLE piece_jointe CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE piece_jointe ADD CONSTRAINT FK_AB5111D480E95E18 FOREIGN KEY (demande_id) REFERENCES demande (id)');
        $this->addSql('CREATE INDEX IDX_AB5111D480E95E18 ON piece_jointe (demande_id)');
        $this->addSql('ALTER TABLE point_nom_conforme CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE point_nom_conforme ADD CONSTRAINT FK_D84A4F411B645EBC FOREIGN KEY (detail_verification_id) REFERENCES detail_verification (id)');
        $this->addSql('CREATE INDEX IDX_D84A4F411B645EBC ON point_nom_conforme (detail_verification_id)');
        $this->addSql('ALTER TABLE proprietaire CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE proprietaire ADD CONSTRAINT FK_69E399D6924DD2B5 FOREIGN KEY (localite_id) REFERENCES localite (id)');
        $this->addSql('CREATE INDEX IDX_69E399D6924DD2B5 ON proprietaire (localite_id)');
        $this->addSql('ALTER TABLE rapport CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE recu CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE recu ADD CONSTRAINT FK_C0D103172A4C4478 FOREIGN KEY (paiement_id) REFERENCES paiement (id)');
        $this->addSql('ALTER TABLE recu ADD CONSTRAINT FK_C0D10317B514973B FOREIGN KEY (caissier_id) REFERENCES agent (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C0D103172A4C4478 ON recu (paiement_id)');
        $this->addSql('CREATE INDEX IDX_C0D10317B514973B ON recu (caissier_id)');
        $this->addSql('ALTER TABLE region CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE reset_password_request CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (id)');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('ALTER TABLE rubrique CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE rubrique ADD CONSTRAINT FK_8FA4097C1DFBCC46 FOREIGN KEY (rapport_id) REFERENCES rapport (id)');
        $this->addSql('CREATE INDEX IDX_8FA4097C1DFBCC46 ON rubrique (rapport_id)');
        $this->addSql('ALTER TABLE tarif ADD cout1 INT NOT NULL, ADD cout2 INT NOT NULL, DROP cout_premier_ins, DROP cout_deuxieme_ins');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9D275ED078');
        $this->addSql('CREATE TABLE accueil (id INT NOT NULL, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, photo VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_by VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE caissier (id INT NOT NULL, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, photo VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_by VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE comptable (id INT NOT NULL, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, photo VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_by VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE controleur (id INT NOT NULL, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, photo VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_by VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE daf (id INT NOT NULL, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, photo VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_by VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE referent (id INT NOT NULL, matricule VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, photo VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_by VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_by VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE respo_front_office (id INT NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE profil');
        $this->addSql('ALTER TABLE affectations_agents MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE affectations_agents DROP FOREIGN KEY FK_73154BD725330D');
        $this->addSql('ALTER TABLE affectations_agents DROP FOREIGN KEY FK_73154B3414710B');
        $this->addSql('DROP INDEX IDX_73154BD725330D ON affectations_agents');
        $this->addSql('DROP INDEX IDX_73154B3414710B ON affectations_agents');
        $this->addSql('ALTER TABLE affectations_agents DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE affectations_agents CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE agence MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE agence DROP FOREIGN KEY FK_64C19AA9924DD2B5');
        $this->addSql('DROP INDEX IDX_64C19AA9924DD2B5 ON agence');
        $this->addSql('ALTER TABLE agence DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE agence CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE agent MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX UNIQ_268B9C9DE7927C74 ON agent');
        $this->addSql('DROP INDEX IDX_268B9C9D275ED078 ON agent');
        $this->addSql('ALTER TABLE agent DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE agent DROP profil_id, DROP id_agence, CHANGE id id INT NOT NULL, CHANGE photo photo VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE attestation MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE attestation DROP FOREIGN KEY FK_326EC63F611C0C56');
        $this->addSql('DROP INDEX UNIQ_326EC63F611C0C56 ON attestation');
        $this->addSql('ALTER TABLE attestation DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE attestation CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE demande MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5FB88E14F');
        $this->addSql('ALTER TABLE demande DROP FOREIGN KEY FK_2694D7A5167B88B4');
        $this->addSql('DROP INDEX IDX_2694D7A5FB88E14F ON demande');
        $this->addSql('DROP INDEX IDX_2694D7A5167B88B4 ON demande');
        $this->addSql('ALTER TABLE demande DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE demande DROP id_paiement, CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE departement MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE departement DROP FOREIGN KEY FK_C1765B6398260155');
        $this->addSql('DROP INDEX IDX_C1765B6398260155 ON departement');
        $this->addSql('ALTER TABLE departement DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE departement CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE detail_verification MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE detail_verification DROP FOREIGN KEY FK_46F2AF043BD38833');
        $this->addSql('ALTER TABLE detail_verification DROP FOREIGN KEY FK_46F2AF041623CB0A');
        $this->addSql('DROP INDEX IDX_46F2AF043BD38833 ON detail_verification');
        $this->addSql('DROP INDEX IDX_46F2AF041623CB0A ON detail_verification');
        $this->addSql('ALTER TABLE detail_verification DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE detail_verification CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE dossier MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E03780E95E18');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E037F4CF9AD9');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E037B13E6101');
        $this->addSql('ALTER TABLE dossier DROP FOREIGN KEY FK_3D48E03735E47E35');
        $this->addSql('DROP INDEX UNIQ_3D48E03780E95E18 ON dossier');
        $this->addSql('DROP INDEX IDX_3D48E037F4CF9AD9 ON dossier');
        $this->addSql('DROP INDEX IDX_3D48E037B13E6101 ON dossier');
        $this->addSql('DROP INDEX IDX_3D48E03735E47E35 ON dossier');
        $this->addSql('ALTER TABLE dossier DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE dossier DROP visite, DROP rapport, DROP attestation, CHANGE id id INT NOT NULL, CHANGE heure_creation heure_creation DATETIME NOT NULL, CHANGE date_cloture date_cloture DATETIME NOT NULL, CHANGE affecte affecte TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE electricien MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE electricien DROP FOREIGN KEY FK_DFB53AEA924DD2B5');
        $this->addSql('DROP INDEX IDX_DFB53AEA924DD2B5 ON electricien');
        $this->addSql('ALTER TABLE electricien DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE electricien CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE grille MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE grille DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE grille CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE installation MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE installation DROP FOREIGN KEY FK_1CBA6AB176C50E4A');
        $this->addSql('ALTER TABLE installation DROP FOREIGN KEY FK_1CBA6AB15C9609E3');
        $this->addSql('ALTER TABLE installation DROP FOREIGN KEY FK_1CBA6AB1924DD2B5');
        $this->addSql('ALTER TABLE installation DROP FOREIGN KEY FK_1CBA6AB1387C850E');
        $this->addSql('ALTER TABLE installation DROP FOREIGN KEY FK_1CBA6AB1B871F14F');
        $this->addSql('ALTER TABLE installation DROP FOREIGN KEY FK_1CBA6AB178EB7775');
        $this->addSql('DROP INDEX IDX_1CBA6AB176C50E4A ON installation');
        $this->addSql('DROP INDEX IDX_1CBA6AB15C9609E3 ON installation');
        $this->addSql('DROP INDEX IDX_1CBA6AB1924DD2B5 ON installation');
        $this->addSql('DROP INDEX IDX_1CBA6AB1387C850E ON installation');
        $this->addSql('DROP INDEX IDX_1CBA6AB1B871F14F ON installation');
        $this->addSql('DROP INDEX IDX_1CBA6AB178EB7775 ON installation');
        $this->addSql('ALTER TABLE installation DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE installation CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE localite MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE localite DROP FOREIGN KEY FK_F5D7E4A9CCF9E01E');
        $this->addSql('DROP INDEX IDX_F5D7E4A9CCF9E01E ON localite');
        $this->addSql('ALTER TABLE localite DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE localite CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE nature_batiment MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE nature_batiment DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE nature_batiment CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE nature_travaux MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE nature_travaux DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE nature_travaux CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE paiement MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E80E95E18');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1EBA52A149');
        $this->addSql('DROP INDEX UNIQ_B1DC7A1E80E95E18 ON paiement');
        $this->addSql('DROP INDEX IDX_B1DC7A1EBA52A149 ON paiement');
        $this->addSql('ALTER TABLE paiement DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE paiement ADD libelle VARCHAR(255) NOT NULL, DROP observation, CHANGE id id INT NOT NULL, CHANGE date_paiement date_paiement DATETIME NOT NULL, CHANGE reference reference VARCHAR(255) NOT NULL, CHANGE motif_remboursement motif_remboursement VARCHAR(255) NOT NULL, CHANGE motif_rejet motif_rejet VARCHAR(255) NOT NULL, CHANGE etat_rembousement etat_rembousement VARCHAR(255) NOT NULL, CHANGE date_saisie date_facture DATETIME NOT NULL');
        $this->addSql('ALTER TABLE piece_jointe MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE piece_jointe DROP FOREIGN KEY FK_AB5111D480E95E18');
        $this->addSql('DROP INDEX IDX_AB5111D480E95E18 ON piece_jointe');
        $this->addSql('ALTER TABLE piece_jointe DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE piece_jointe CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE point_nom_conforme MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE point_nom_conforme DROP FOREIGN KEY FK_D84A4F411B645EBC');
        $this->addSql('DROP INDEX IDX_D84A4F411B645EBC ON point_nom_conforme');
        $this->addSql('ALTER TABLE point_nom_conforme DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE point_nom_conforme CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE proprietaire MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE proprietaire DROP FOREIGN KEY FK_69E399D6924DD2B5');
        $this->addSql('DROP INDEX IDX_69E399D6924DD2B5 ON proprietaire');
        $this->addSql('ALTER TABLE proprietaire DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE proprietaire CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE rapport MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE rapport DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE rapport CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE recu MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE recu DROP FOREIGN KEY FK_C0D103172A4C4478');
        $this->addSql('ALTER TABLE recu DROP FOREIGN KEY FK_C0D10317B514973B');
        $this->addSql('DROP INDEX UNIQ_C0D103172A4C4478 ON recu');
        $this->addSql('DROP INDEX IDX_C0D10317B514973B ON recu');
        $this->addSql('ALTER TABLE recu DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE recu CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE region MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE region DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE region CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE reset_password_request MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('DROP INDEX IDX_7CE748AA76ED395 ON reset_password_request');
        $this->addSql('ALTER TABLE reset_password_request DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE reset_password_request CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE rubrique MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE rubrique DROP FOREIGN KEY FK_8FA4097C1DFBCC46');
        $this->addSql('DROP INDEX IDX_8FA4097C1DFBCC46 ON rubrique');
        $this->addSql('ALTER TABLE rubrique DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE rubrique CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE tarif ADD cout_premier_ins INT NOT NULL, ADD cout_deuxieme_ins INT NOT NULL, DROP cout1, DROP cout2');
        $this->addSql('ALTER TABLE visite DROP FOREIGN KEY FK_B09C8CBB611C0C56');
    }
}
