<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE86xryi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE86xryi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerE86xryi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerE86xryi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerE86xryi\App_KernelProdContainer([
    'container.build_hash' => 'E86xryi',
    'container.build_id' => '7691186c',
    'container.build_time' => 1660911553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE86xryi');
