<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agent extends \App\Entity\Agent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'id_agence', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'profil', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'recu', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'paiement', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'dossierControleur', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'dossierReferent', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'dossierRFO', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'affectation', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'tof', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'created_by', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'updated_by'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'id_agence', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'profil', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'recu', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'paiement', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'dossierControleur', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'dossierReferent', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'dossierRFO', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'affectation', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'tof', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'created_by', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Agent' . "\0" . 'updated_by'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(string $matricule): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfil(): ?\App\Entity\Profil
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfil', []);

        return parent::getProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfil(?\App\Entity\Profil $profil): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfil', [$profil]);

        return parent::setProfil($profil);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAgence(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAgence', []);

        return parent::getIdAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAgence(?int $id_agence): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAgence', [$id_agence]);

        return parent::setIdAgence($id_agence);
    }

    /**
     * {@inheritDoc}
     */
    public function getTof(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTof', []);

        return parent::getTof();
    }

    /**
     * {@inheritDoc}
     */
    public function setTof(\Symfony\Component\HttpFoundation\File\File $tof): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTof', [$tof]);

        return parent::setTof($tof);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffectation(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffectation', []);

        return parent::getAffectation();
    }

    /**
     * {@inheritDoc}
     */
    public function getAgence(): ?\App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgence', []);

        return parent::getAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function addAffectation(\App\Entity\AffectationsAgents $affectation): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAffectation', [$affectation]);

        return parent::addAffectation($affectation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAffectation(\App\Entity\AffectationsAgents $affectation): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAffectation', [$affectation]);

        return parent::removeAffectation($affectation);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecu(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecu', []);

        return parent::getRecu();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecu(\App\Entity\Recu $recu): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecu', [$recu]);

        return parent::addRecu($recu);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecu(\App\Entity\Recu $recu): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecu', [$recu]);

        return parent::removeRecu($recu);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', []);

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function addPaiement(\App\Entity\Paiement $paiement): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaiement', [$paiement]);

        return parent::addPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaiement(\App\Entity\Paiement $paiement): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaiement', [$paiement]);

        return parent::removePaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierActifReferent(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierActifReferent', []);

        return parent::getDossierActifReferent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierReferent(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierReferent', []);

        return parent::getDossierReferent();
    }

    /**
     * {@inheritDoc}
     */
    public function addDossierReferent(\App\Entity\Dossier $dossier): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDossierReferent', [$dossier]);

        return parent::addDossierReferent($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDossierReferent(\App\Entity\Dossier $dossier): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDossierReferent', [$dossier]);

        return parent::removeDossierReferent($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierControleur(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierControleur', []);

        return parent::getDossierControleur();
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierActifControleur(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierActifControleur', []);

        return parent::getDossierActifControleur();
    }

    /**
     * {@inheritDoc}
     */
    public function addDossierControleur(\App\Entity\Dossier $dossier): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDossierControleur', [$dossier]);

        return parent::addDossierControleur($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDossierControleur(\App\Entity\Dossier $dossier): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDossierControleur', [$dossier]);

        return parent::removeDossierControleur($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierRFO(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierRFO', []);

        return parent::getDossierRFO();
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierActifRFO(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierActifRFO', []);

        return parent::getDossierActifRFO();
    }

    /**
     * {@inheritDoc}
     */
    public function addDossierRFO(\App\Entity\Dossier $dossier): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDossierRFO', [$dossier]);

        return parent::addDossierRFO($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDossierRFO(\App\Entity\Dossier $dossier): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDossierRFO', [$dossier]);

        return parent::removeDossierRFO($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenceCourante(): ?\App\Entity\Agence
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenceCourante', []);

        return parent::getAgenceCourante();
    }

    /**
     * {@inheritDoc}
     */
    public function nomComplet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nomComplet', []);

        return parent::nomComplet();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $created_at): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeImmutable $updated_at): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedby(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedby', []);

        return parent::getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedby(string $created_by): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedby', [$created_by]);

        return parent::setCreatedby($created_by);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(string $updated_by): \App\Entity\Agent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updated_by]);

        return parent::setUpdatedBy($updated_by);
    }

}
