<?php

namespace Container3M2iWAM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LFxlOIjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lFxlOIj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lFxlOIj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'id' => ['privates', '.errored..service_locator.lFxlOIj.App\\Entity\\Agent', NULL, 'Cannot autowire service ".service_locator.lFxlOIj": it references class "App\\Entity\\Agent" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'id' => 'App\\Entity\\Agent',
        ]);
    }
}
