<?php

namespace ContainerLWeHzfk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0VVL9j5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0VVL9j5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0VVL9j5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'departementRepository' => ['privates', 'App\\Repository\\DepartementRepository', 'getDepartementRepositoryService', true],
        ], [
            'departementRepository' => 'App\\Repository\\DepartementRepository',
        ]);
    }
}
