<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NxHtltOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NxHtltO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NxHtltO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'natureTravaux' => ['privates', '.errored..service_locator.NxHtltO.App\\Entity\\NatureTravaux', NULL, 'Cannot autowire service ".service_locator.NxHtltO": it references class "App\\Entity\\NatureTravaux" but no such service exists.'],
            'natureTravauxRepository' => ['privates', 'App\\Repository\\NatureTravauxRepository', 'getNatureTravauxRepositoryService', true],
        ], [
            'natureTravaux' => 'App\\Entity\\NatureTravaux',
            'natureTravauxRepository' => 'App\\Repository\\NatureTravauxRepository',
        ]);
    }
}
