<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GLfu7rXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GLfu7rX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GLfu7rX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandeRepository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'installation' => ['privates', '.errored..service_locator.GLfu7rX.App\\Entity\\Installation', NULL, 'Cannot autowire service ".service_locator.GLfu7rX": it references class "App\\Entity\\Installation" but no such service exists.'],
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'demandeRepository' => 'App\\Repository\\DemandeRepository',
            'doctrine' => '?',
            'installation' => 'App\\Entity\\Installation',
            'installationRepository' => 'App\\Repository\\InstallationRepository',
            'mailer' => '?',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
