<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QYBAVNqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QYBAVNq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QYBAVNq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demande' => ['privates', '.errored..service_locator.QYBAVNq.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.QYBAVNq": it references class "App\\Entity\\Demande" but no such service exists.'],
            'demandeRepository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'demande' => 'App\\Entity\\Demande',
            'demandeRepository' => 'App\\Repository\\DemandeRepository',
            'em' => '?',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
