<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SRCPwipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SRCPwip' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SRCPwip'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'installation' => ['privates', '.errored..service_locator.SRCPwip.App\\Entity\\Installation', NULL, 'Cannot autowire service ".service_locator.SRCPwip": it references class "App\\Entity\\Installation" but no such service exists.'],
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
            'pjRepository' => ['privates', 'App\\Repository\\PieceJointeRepository', 'getPieceJointeRepositoryService', true],
            'proprietaireRepository' => ['privates', 'App\\Repository\\ProprietaireRepository', 'getProprietaireRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'installation' => 'App\\Entity\\Installation',
            'installationRepository' => 'App\\Repository\\InstallationRepository',
            'pjRepository' => 'App\\Repository\\PieceJointeRepository',
            'proprietaireRepository' => 'App\\Repository\\ProprietaireRepository',
            'slugger' => '?',
        ]);
    }
}
