<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIajp4JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jIajp4J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jIajp4J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'localiteRepository' => ['privates', 'App\\Repository\\LocaliteRepository', 'getLocaliteRepositoryService', true],
        ], [
            'localiteRepository' => 'App\\Repository\\LocaliteRepository',
        ]);
    }
}
