<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5WAyRFZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5WAyRFZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5WAyRFZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paiement' => ['privates', '.errored..service_locator.5WAyRFZ.App\\Entity\\Paiement', NULL, 'Cannot autowire service ".service_locator.5WAyRFZ": it references class "App\\Entity\\Paiement" but no such service exists.'],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
            'remboursementRepository' => ['privates', 'App\\Repository\\RemboursementRepository', 'getRemboursementRepositoryService', true],
        ], [
            'paiement' => 'App\\Entity\\Paiement',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
            'remboursementRepository' => 'App\\Repository\\RemboursementRepository',
        ]);
    }
}
