<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MhevkXHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mhevkXH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mhevkXH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pointNonconfRepository' => ['privates', 'App\\Repository\\PointNonconfRepository', 'getPointNonconfRepositoryService', true],
            'pointVerification' => ['privates', '.errored..service_locator.mhevkXH.App\\Entity\\PointVerification', NULL, 'Cannot autowire service ".service_locator.mhevkXH": it references class "App\\Entity\\PointVerification" but no such service exists.'],
            'pointVerificationRepository' => ['privates', 'App\\Repository\\PointVerificationRepository', 'getPointVerificationRepositoryService', true],
        ], [
            'pointNonconfRepository' => 'App\\Repository\\PointNonconfRepository',
            'pointVerification' => 'App\\Entity\\PointVerification',
            'pointVerificationRepository' => 'App\\Repository\\PointVerificationRepository',
        ]);
    }
}
