<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OAQA4e8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OAQA4e8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OAQA4e8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'dossierRepository' => ['privates', 'App\\Repository\\DossierRepository', 'getDossierRepositoryService', true],
            'pgn' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'doctrine' => '?',
            'dossierRepository' => 'App\\Repository\\DossierRepository',
            'pgn' => '?',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
