<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5FhXLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._5Fh_XL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._5Fh_XL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'proprietaireRepository' => ['privates', 'App\\Repository\\ProprietaireRepository', 'getProprietaireRepositoryService', true],
        ], [
            'proprietaireRepository' => 'App\\Repository\\ProprietaireRepository',
        ]);
    }
}
