<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2P8XAvUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2P8XAvU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2P8XAvU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'dossier' => ['privates', '.errored..service_locator.2P8XAvU.App\\Entity\\Dossier', NULL, 'Cannot autowire service ".service_locator.2P8XAvU": it references class "App\\Entity\\Dossier" but no such service exists.'],
            'dossierRepository' => ['privates', 'App\\Repository\\DossierRepository', 'getDossierRepositoryService', true],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'doctrine' => '?',
            'dossier' => 'App\\Entity\\Dossier',
            'dossierRepository' => 'App\\Repository\\DossierRepository',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
