<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2HnPRL4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2HnPRL4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2HnPRL4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demande' => ['privates', '.errored..service_locator.2HnPRL4.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.2HnPRL4": it references class "App\\Entity\\Demande" but no such service exists.'],
            'demandeRepository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'tools' => ['privates', 'App\\Services\\Tools', 'getToolsService', true],
        ], [
            'demande' => 'App\\Entity\\Demande',
            'demandeRepository' => 'App\\Repository\\DemandeRepository',
            'doctrine' => '?',
            'tools' => 'App\\Services\\Tools',
        ]);
    }
}
