<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FKsjWv7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FKsjWv7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FKsjWv7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'natureTravaux' => ['privates', '.errored..service_locator.FKsjWv7.App\\Entity\\NatureTravaux', NULL, 'Cannot autowire service ".service_locator.FKsjWv7": it references class "App\\Entity\\NatureTravaux" but no such service exists.'],
        ], [
            'natureTravaux' => 'App\\Entity\\NatureTravaux',
        ]);
    }
}
