<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemande4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8w9KbvG.App\Entity\Demande' shared service.
     *
     * @return \App\Entity\Demande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8w9KbvG": it references class "App\\Entity\\Demande" but no such service exists.');
    }
}
