<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossier4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A.RUheC.App\Entity\Dossier' shared service.
     *
     * @return \App\Entity\Dossier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A.RUheC": it references class "App\\Entity\\Dossier" but no such service exists.');
    }
}
