<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeoArrayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Geocoder\Dumper\GeoArray' shared service.
     *
     * @return \Geocoder\Dumper\GeoArray
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Dumper/AbstractArrayDumper.php';
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Dumper/Dumper.php';
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Dumper/GeoArray.php';

        return $container->services['Geocoder\\Dumper\\GeoArray'] = new \Geocoder\Dumper\GeoArray();
    }
}
