<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Tools' shared autowired service.
     *
     * @return \App\Services\Tools
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/Tools.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/BuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/endroid/qr-code/src/Builder/Builder.php';

        return $container->privates['App\\Services\\Tools'] = new \App\Services\Tools(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), new \Endroid\QrCode\Builder\Builder(), 'yatamala.net@gmail.com', 'Notification COSSUEL');
    }
}
