<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWktService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Geocoder\Dumper\Wkt' shared service.
     *
     * @return \Geocoder\Dumper\Wkt
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Dumper/Dumper.php';
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Dumper/Wkt.php';

        return $container->services['Geocoder\\Dumper\\Wkt'] = new \Geocoder\Dumper\Wkt();
    }
}
