<?php

namespace ContainerJa7qilq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JzNEKqLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jzNEKqL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jzNEKqL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
        ], [
            'installationRepository' => 'App\\Repository\\InstallationRepository',
        ]);
    }
}
