<?php

namespace ContainerWDqPXep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BHt6OdaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BHt6Oda' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BHt6Oda'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.BHt6Oda.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.BHt6Oda": it references class "App\\Entity\\Client" but no such service exists.'],
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
        ], [
            'client' => 'App\\Entity\\Client',
            'clientRepository' => 'App\\Repository\\ClientRepository',
        ]);
    }
}
