<?php

namespace ContainerWDqPXep;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.s20cVQa.App\Entity\Installation' shared service.
     *
     * @return \App\Entity\Installation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.s20cVQa": it references class "App\\Entity\\Installation" but no such service exists.');
    }
}
