<?php

namespace Container12vlQi2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9gfGPgDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9gfGPgD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9gfGPgD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'localiteRepository' => ['privates', 'App\\Repository\\LocaliteRepository', 'getLocaliteRepositoryService', true],
            'slug' => ['privates', '.errored..service_locator.9gfGPgD.App\\Entity\\Localite', NULL, 'Cannot autowire service ".service_locator.9gfGPgD": it references class "App\\Entity\\Localite" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'localiteRepository' => 'App\\Repository\\LocaliteRepository',
            'slug' => 'App\\Entity\\Localite',
        ]);
    }
}
