<?php

namespace Container12vlQi2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lFxlOIj.App\Entity\Agent' shared service.
     *
     * @return \App\Entity\Agent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lFxlOIj": it references class "App\\Entity\\Agent" but no such service exists.');
    }
}
