<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D5Kf2ZLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D5Kf2ZL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D5Kf2ZL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandeRepo' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'installation' => ['privates', '.errored..service_locator.D5Kf2ZL.App\\Entity\\Installation', NULL, 'Cannot autowire service ".service_locator.D5Kf2ZL": it references class "App\\Entity\\Installation" but no such service exists.'],
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
        ], [
            'demandeRepo' => 'App\\Repository\\DemandeRepository',
            'installation' => 'App\\Entity\\Installation',
            'installationRepository' => 'App\\Repository\\InstallationRepository',
        ]);
    }
}
