<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4vKPy8tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4vKPy8t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4vKPy8t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'dossier' => ['privates', '.errored..service_locator.4vKPy8t.App\\Entity\\Dossier', NULL, 'Cannot autowire service ".service_locator.4vKPy8t": it references class "App\\Entity\\Dossier" but no such service exists.'],
            'dossierRepository' => ['privates', 'App\\Repository\\DossierRepository', 'getDossierRepositoryService', true],
        ], [
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'dossier' => 'App\\Entity\\Dossier',
            'dossierRepository' => 'App\\Repository\\DossierRepository',
        ]);
    }
}
