<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MIz3BtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mIz3Bto' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mIz3Bto'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pointVerification' => ['privates', '.errored..service_locator.mIz3Bto.App\\Entity\\PointVerification', NULL, 'Cannot autowire service ".service_locator.mIz3Bto": it references class "App\\Entity\\PointVerification" but no such service exists.'],
            'pointVerificationRepository' => ['privates', 'App\\Repository\\PointVerificationRepository', 'getPointVerificationRepositoryService', true],
            'rubriqueRepository' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService', true],
        ], [
            'pointVerification' => 'App\\Entity\\PointVerification',
            'pointVerificationRepository' => 'App\\Repository\\PointVerificationRepository',
            'rubriqueRepository' => 'App\\Repository\\RubriqueRepository',
        ]);
    }
}
