<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HvOBdAsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hvOBdAs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hvOBdAs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'installation' => ['privates', '.errored..service_locator.hvOBdAs.App\\Entity\\Installation', NULL, 'Cannot autowire service ".service_locator.hvOBdAs": it references class "App\\Entity\\Installation" but no such service exists.'],
            'installationRepository' => ['privates', 'App\\Repository\\InstallationRepository', 'getInstallationRepositoryService', true],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
        ], [
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'doctrine' => '?',
            'installation' => 'App\\Entity\\Installation',
            'installationRepository' => 'App\\Repository\\InstallationRepository',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
        ]);
    }
}
