<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ITgATMgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iTgATMg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iTgATMg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agaffRepository' => ['privates', 'App\\Repository\\AffectationsAgentsRepository', 'getAffectationsAgentsRepositoryService', true],
            'agenceRepository' => ['privates', 'App\\Repository\\AgenceRepository', 'getAgenceRepositoryService', true],
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'agaffRepository' => 'App\\Repository\\AffectationsAgentsRepository',
            'agenceRepository' => 'App\\Repository\\AgenceRepository',
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'doctrine' => '?',
            'slugger' => '?',
        ]);
    }
}
