<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallation7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hvOBdAs.App\Entity\Installation' shared service.
     *
     * @return \App\Entity\Installation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hvOBdAs": it references class "App\\Entity\\Installation" but no such service exists.');
    }
}
