<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointVerification2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mIz3Bto.App\Entity\PointVerification' shared service.
     *
     * @return \App\Entity\PointVerification
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mIz3Bto": it references class "App\\Entity\\PointVerification" but no such service exists.');
    }
}
