<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProviderAggregatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Geocoder\ProviderAggregator' shared service.
     *
     * @return \Geocoder\ProviderAggregator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Provider/Provider.php';
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/Geocoder.php';
        include_once \dirname(__DIR__, 4).'/vendor/willdurand/geocoder/ProviderAggregator.php';

        $container->privates['Geocoder\\ProviderAggregator'] = $instance = new \Geocoder\ProviderAggregator();

        $instance->registerProviders([]);

        return $instance;
    }
}
