<?php

namespace ContainerBt2szyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemboursement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X1Q0ly0.App\Entity\Remboursement' shared service.
     *
     * @return \App\Entity\Remboursement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.X1Q0ly0": it references class "App\\Entity\\Remboursement" but no such service exists.');
    }
}
