<?php

namespace ContainerZu7ox15;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SQT9DfJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sQT9DfJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sQT9DfJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
        ], [
            'regionRepository' => 'App\\Repository\\RegionRepository',
        ]);
    }
}
