<?php

namespace ContainerZu7ox15;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YFkO9hxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yFkO9hx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yFkO9hx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DepartementController::add' => ['privates', '.service_locator.iMwAaCC', 'get_ServiceLocator_IMwAaCCService', true],
            'App\\Controller\\DepartementController::edit' => ['privates', '.service_locator.yOp7iqO', 'get_ServiceLocator_YOp7iqOService', true],
            'App\\Controller\\DepartementController::index' => ['privates', '.service_locator.0VVL9j5', 'get_ServiceLocator_0VVL9j5Service', true],
            'App\\Controller\\DepartementController::show' => ['privates', '.service_locator.yOp7iqO', 'get_ServiceLocator_YOp7iqOService', true],
            'App\\Controller\\RegionController::add' => ['privates', '.service_locator.CLw.7PQ', 'get_ServiceLocator_CLw_7PQService', true],
            'App\\Controller\\RegionController::edit' => ['privates', '.service_locator.ROkM79E', 'get_ServiceLocator_ROkM79EService', true],
            'App\\Controller\\RegionController::index' => ['privates', '.service_locator.sQT9DfJ', 'get_ServiceLocator_SQT9DfJService', true],
            'App\\Controller\\RegionController::show' => ['privates', '.service_locator.ROkM79E', 'get_ServiceLocator_ROkM79EService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.1g4809_', 'get_ServiceLocator_1g4809Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.D4nGOut', 'get_ServiceLocator_D4nGOutService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.LI1wy7E', 'get_ServiceLocator_LI1wy7EService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DepartementController:add' => ['privates', '.service_locator.iMwAaCC', 'get_ServiceLocator_IMwAaCCService', true],
            'App\\Controller\\DepartementController:edit' => ['privates', '.service_locator.yOp7iqO', 'get_ServiceLocator_YOp7iqOService', true],
            'App\\Controller\\DepartementController:index' => ['privates', '.service_locator.0VVL9j5', 'get_ServiceLocator_0VVL9j5Service', true],
            'App\\Controller\\DepartementController:show' => ['privates', '.service_locator.yOp7iqO', 'get_ServiceLocator_YOp7iqOService', true],
            'App\\Controller\\RegionController:add' => ['privates', '.service_locator.CLw.7PQ', 'get_ServiceLocator_CLw_7PQService', true],
            'App\\Controller\\RegionController:edit' => ['privates', '.service_locator.ROkM79E', 'get_ServiceLocator_ROkM79EService', true],
            'App\\Controller\\RegionController:index' => ['privates', '.service_locator.sQT9DfJ', 'get_ServiceLocator_SQT9DfJService', true],
            'App\\Controller\\RegionController:show' => ['privates', '.service_locator.ROkM79E', 'get_ServiceLocator_ROkM79EService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.1g4809_', 'get_ServiceLocator_1g4809Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.D4nGOut', 'get_ServiceLocator_D4nGOutService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.LI1wy7E', 'get_ServiceLocator_LI1wy7EService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DepartementController::add' => '?',
            'App\\Controller\\DepartementController::edit' => '?',
            'App\\Controller\\DepartementController::index' => '?',
            'App\\Controller\\DepartementController::show' => '?',
            'App\\Controller\\RegionController::add' => '?',
            'App\\Controller\\RegionController::edit' => '?',
            'App\\Controller\\RegionController::index' => '?',
            'App\\Controller\\RegionController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DepartementController:add' => '?',
            'App\\Controller\\DepartementController:edit' => '?',
            'App\\Controller\\DepartementController:index' => '?',
            'App\\Controller\\DepartementController:show' => '?',
            'App\\Controller\\RegionController:add' => '?',
            'App\\Controller\\RegionController:edit' => '?',
            'App\\Controller\\RegionController:index' => '?',
            'App\\Controller\\RegionController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
