<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJVmEO8H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJVmEO8H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJVmEO8H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJVmEO8H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJVmEO8H\App_KernelDevDebugContainer([
    'container.build_hash' => 'JVmEO8H',
    'container.build_id' => 'a8da955c',
    'container.build_time' => 1649710924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJVmEO8H');
