<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQuesjqN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQuesjqN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQuesjqN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQuesjqN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQuesjqN\App_KernelDevDebugContainer([
    'container.build_hash' => 'QuesjqN',
    'container.build_id' => '692260f1',
    'container.build_time' => 1650289649,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQuesjqN');
