<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Attestation extends \App\Entity\Attestation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateDelivrance', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'synchronise1', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateSynchro1', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'synchronise2', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateSynchro2', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'avis', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateAvis', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'compteur', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'contrat', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateContrat', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'comptabilisateur', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'finalisateur', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'agenceComptabilise', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'created_by', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'updated_by'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateDelivrance', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'synchronise1', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateSynchro1', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'synchronise2', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateSynchro2', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'avis', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateAvis', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'compteur', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'contrat', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dateContrat', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'comptabilisateur', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'finalisateur', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'agenceComptabilise', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'created_by', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Attestation' . "\0" . 'updated_by'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Attestation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(int $numero): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDelivrance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDelivrance', []);

        return parent::getDateDelivrance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDelivrance(\DateTimeInterface $dateDelivrance): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDelivrance', [$dateDelivrance]);

        return parent::setDateDelivrance($dateDelivrance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossier(): ?\App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossier', []);

        return parent::getDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDossier(?\App\Entity\Dossier $dossier): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDossier', [$dossier]);

        return parent::setDossier($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenceComptabilise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenceComptabilise', []);

        return parent::getAgenceComptabilise();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgenceComptabilise(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgenceComptabilise', [$val]);

        return parent::setAgenceComptabilise($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalisateur', []);

        return parent::getFinalisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalisateur(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalisateur', [$val]);

        return parent::setFinalisateur($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getComptabilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComptabilisateur', []);

        return parent::getComptabilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setComptabilisateur(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComptabilisateur', [$val]);

        return parent::setComptabilisateur($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getSynchronise1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSynchronise1', []);

        return parent::getSynchronise1();
    }

    /**
     * {@inheritDoc}
     */
    public function setSynchronise1(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSynchronise1', [$val]);

        return parent::setSynchronise1($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getSynchronise2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSynchronise2', []);

        return parent::getSynchronise2();
    }

    /**
     * {@inheritDoc}
     */
    public function setSynchronise2(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSynchronise2', [$val]);

        return parent::setSynchronise2($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvis(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvis', []);

        return parent::getAvis();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvis(?string $avis): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvis', [$avis]);

        return parent::setAvis($avis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAvis(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAvis', []);

        return parent::getDateAvis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAvis(?string $dateAvis): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAvis', [$dateAvis]);

        return parent::setDateAvis($dateAvis);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteur', []);

        return parent::getCompteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteur(?string $compteur): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteur', [$compteur]);

        return parent::setCompteur($compteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrat', []);

        return parent::getContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrat(?string $Contrat): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrat', [$Contrat]);

        return parent::setContrat($Contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateContrat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateContrat', []);

        return parent::getDateContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateContrat(?string $Contrat): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateContrat', [$Contrat]);

        return parent::setDateContrat($Contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSynchro1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSynchro1', []);

        return parent::getDateSynchro1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSynchro1(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSynchro1', [$val]);

        return parent::setDateSynchro1($val);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSynchro2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSynchro2', []);

        return parent::getDateSynchro2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSynchro2(?string $val): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSynchro2', [$val]);

        return parent::setDateSynchro2($val);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeImmutable $created_at): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeImmutable $updated_at): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedby(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedby', []);

        return parent::getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedby(string $created_by): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedby', [$created_by]);

        return parent::setCreatedby($created_by);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(string $updated_by): \App\Entity\Attestation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updated_by]);

        return parent::setUpdatedBy($updated_by);
    }

}
